name: Secrets
run-name: Esto es un secreto
on: 
  workflow_dispatch
jobs:
  ejecutar-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir secreto
        run: echo "Tu contraseña es ${{ secrets.PASSWORD }}"
